Renaming MCS and Mobile Client Service to MDC and Mobile Developer Co…
aerogearcatalog/mobile-developer-console-apb pull request #4
Opened 2018-09-26 12:48 UTC by secondsun

How to test : 

1. Have Openshift running with the ansible service broker
2. Have APB installed (you will need an older version, the latest versions have changed most of the commands)
3. apb build
4. apb push
5. Deploy Mobile Developer Console from the catalog
6. profit!

2018-09-27 06:28 UTC, jhellar reviewed
I left few comments. Also whole `roles` folder was removed. Without it it won't work, right?

2018-09-27 06:28 UTC, jhellar commented on Makefile
>  IMAGENAME = mobile-client-service-apb
Should we also rename `IMAGENAME `?

2018-09-27 06:28 UTC, jhellar commented on Makefile
> +DOCKERORG = sagaoftherealms
Is this just for testing? Should not it be `aerogearcatalog`?

2018-09-27 06:28 UTC, jhellar commented on apb.yml
> +      - "docker.io/aerogearcatalog/mobile-client-service:latest"
Should not the service (mdc server) image be in `aerogear` org as other services?

2018-09-27 12:48 UTC, secondsun commented
@jhellar role being removed was a mistake, I renamed the folders but I didn't git add them correctly ><

2018-09-27 13:03 UTC, secondsun commented
@jhellar I think it should be aerogearcatalog and not aerogear because that is the repository mobile-core is looking at.  I can't find guidance one way or another though.

2018-09-28 14:41 UTC, secondsun commented
@jhellar Any more thoughts?

2018-09-28 18:41 UTC, danielpassos requested changes

2018-09-28 18:41 UTC, danielpassos commented on roles/provision-mdc-server-apb/defaults/main.yml
> +mobile_developer_console_image: "docker.io/aerogear/mobile-client-service"
Should be `mobile-developer-console` instead of `mobile-client-service`?

2018-09-28 18:51 UTC, secondsun commented
@danielpassos fixes

2018-09-28 18:52 UTC, danielpassos approved these changes
<img width="1440" alt="screenshot 2018-09-28 15 49 14" src="https://user-images.githubusercontent.com/13337/46227759-89a8ee00-c336-11e8-822c-ba0332466156.png">

2018-09-28 19:01 UTC, merged